const countries = [
  {
    name: 'Afghanistan',
    id: 'AF',
    capital: 'Kabul',
    region: 'AS',
    currency: {
      id: 'AFN',
      name: 'Afghan afghani',
      symbol: '؋',
    },
    language: {
      id: 'ps',
      name: 'Pashto',
    },
    flag: 'https://restcountries.eu/data/afg.svg',
  },
  {
    name: 'Åland Islands',
    id: 'AX',
    capital: 'Mariehamn',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'sv',
      name: 'Swedish',
    },
    flag: 'https://restcountries.eu/data/ala.svg',
  },
  {
    name: 'Albania',
    id: 'AL',
    capital: 'Tirana',
    region: 'EU',
    currency: {
      id: 'ALL',
      name: 'Albanian lek',
      symbol: 'L',
    },
    language: {
      id: 'sq',
      name: 'Albanian',
    },
    flag: 'https://restcountries.eu/data/alb.svg',
  },
  {
    name: 'Algeria',
    id: 'DZ',
    capital: 'Algiers',
    region: 'AF',
    currency: {
      id: 'DZD',
      name: 'Algerian dinar',
      symbol: 'د.ج',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/dza.svg',
  },
  {
    name: 'American Samoa',
    id: 'AS',
    capital: 'Pago Pago',
    region: 'OC',
    currency: {
      id: 'USD',
      name: 'United State Dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/asm.svg',
  },
  {
    name: 'Andorra',
    id: 'AD',
    capital: 'Andorra la Vella',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'ca',
      name: 'Catalan',
    },
    flag: 'https://restcountries.eu/data/and.svg',
  },
  {
    name: 'Angola',
    id: 'AO',
    capital: 'Luanda',
    region: 'AF',
    currency: {
      id: 'AOA',
      name: 'Angolan kwanza',
      symbol: 'Kz',
    },
    language: {
      id: 'pt',
      name: 'Portuguese',
    },
    flag: 'https://restcountries.eu/data/ago.svg',
  },
  {
    name: 'Anguilla',
    id: 'AI',
    capital: 'The Valley',
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/aia.svg',
  },
  {
    name: 'Antigua and Barbuda',
    id: 'AG',
    capital: "Saint John's",
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/atg.svg',
  },
  {
    name: 'Argentina',
    id: 'AR',
    capital: 'Buenos Aires',
    region: 'SA',
    currency: {
      id: 'ARS',
      name: 'Argentine peso',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/arg.svg',
  },
  {
    name: 'Armenia',
    id: 'AM',
    capital: 'Yerevan',
    region: 'AS',
    currency: {
      id: 'AMD',
      name: 'Armenian dram',
      symbol: null,
    },
    language: {
      id: 'hy',
      name: 'Armenian',
    },
    flag: 'https://restcountries.eu/data/arm.svg',
  },
  {
    name: 'Aruba',
    id: 'AW',
    capital: 'Oranjestad',
    region: 'SA',
    currency: {
      id: 'AWG',
      name: 'Aruban florin',
      symbol: 'ƒ',
    },
    language: {
      id: 'nl',
      name: 'Dutch',
    },
    flag: 'https://restcountries.eu/data/abw.svg',
  },
  {
    name: 'Australia',
    id: 'AU',
    capital: 'Canberra',
    region: 'OC',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/aus.svg',
  },
  {
    name: 'Austria',
    id: 'AT',
    capital: 'Vienna',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'de',
      name: 'German',
    },
    flag: 'https://restcountries.eu/data/aut.svg',
  },
  {
    name: 'Azerbaijan',
    id: 'AZ',
    capital: 'Baku',
    region: 'AS',
    currency: {
      id: 'AZN',
      name: 'Azerbaijani manat',
      symbol: null,
    },
    language: {
      id: 'az',
      name: 'Azerbaijani',
    },
    flag: 'https://restcountries.eu/data/aze.svg',
  },
  {
    name: 'Bahamas',
    id: 'BS',
    capital: 'Nassau',
    region: 'NA',
    currency: {
      id: 'BSD',
      name: 'Bahamian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/bhs.svg',
  },
  {
    name: 'Bahrain',
    id: 'BH',
    capital: 'Manama',
    region: 'AS',
    currency: {
      id: 'BHD',
      name: 'Bahraini dinar',
      symbol: '.د.ب',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/bhr.svg',
  },
  {
    name: 'Bangladesh',
    id: 'BD',
    capital: 'Dhaka',
    region: 'AS',
    currency: {
      id: 'BDT',
      name: 'Bangladeshi taka',
      symbol: '৳',
    },
    language: {
      id: 'bn',
      name: 'Bengali',
    },
    flag: 'https://restcountries.eu/data/bgd.svg',
  },
  {
    name: 'Barbados',
    id: 'BB',
    capital: 'Bridgetown',
    region: 'NA',
    currency: {
      id: 'BBD',
      name: 'Barbadian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/brb.svg',
  },
  {
    name: 'Belarus',
    id: 'BY',
    capital: 'Minsk',
    region: 'EU',
    currency: {
      id: 'BYN',
      name: 'New Belarusian ruble',
      symbol: 'Br',
    },
    language: {
      id: 'be',
      name: 'Belarusian',
    },
    flag: 'https://restcountries.eu/data/blr.svg',
  },
  {
    name: 'Belgium',
    id: 'BE',
    capital: 'Brussels',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'nl',
      name: 'Dutch',
    },
    flag: 'https://restcountries.eu/data/bel.svg',
  },
  {
    name: 'Belize',
    id: 'BZ',
    capital: 'Belmopan',
    region: 'NA',
    currency: {
      id: 'BZD',
      name: 'Belize dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/blz.svg',
  },
  {
    name: 'Benin',
    id: 'BJ',
    capital: 'Porto-Novo',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/ben.svg',
  },
  {
    name: 'Bermuda',
    id: 'BM',
    capital: 'Hamilton',
    region: 'NA',
    currency: {
      id: 'BMD',
      name: 'Bermudian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/bmu.svg',
  },
  {
    name: 'Bhutan',
    id: 'BT',
    capital: 'Thimphu',
    region: 'AS',
    currency: {
      id: 'BTN',
      name: 'Bhutanese ngultrum',
      symbol: 'Nu.',
    },
    language: {
      id: 'dz',
      name: 'Dzongkha',
    },
    flag: 'https://restcountries.eu/data/btn.svg',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    id: 'BO',
    capital: 'Sucre',
    region: 'SA',
    currency: {
      id: 'BOB',
      name: 'Bolivian boliviano',
      symbol: 'Bs.',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/bol.svg',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    id: 'BQ',
    capital: 'Kralendijk',
    region: 'SA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'nl',
      name: 'Dutch',
    },
    flag: 'https://restcountries.eu/data/bes.svg',
  },
  {
    name: 'Bosnia and Herzegovina',
    id: 'BA',
    capital: 'Sarajevo',
    region: 'EU',
    currency: {
      id: 'BAM',
      name: 'Bosnia and Herzegovina convertible mark',
      symbol: null,
    },
    language: {
      id: 'bs',
      name: 'Bosnian',
    },
    flag: 'https://restcountries.eu/data/bih.svg',
  },
  {
    name: 'Botswana',
    id: 'BW',
    capital: 'Gaborone',
    region: 'AF',
    currency: {
      id: 'BWP',
      name: 'Botswana pula',
      symbol: 'P',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/bwa.svg',
  },
  {
    name: 'Bouvet Island',
    id: 'BV',
    capital: '',
    region: 'AN',
    currency: {
      id: 'NOK',
      name: 'Norwegian krone',
      symbol: 'kr',
    },
    language: {
      id: 'no',
      name: 'Norwegian',
    },
    flag: 'https://restcountries.eu/data/bvt.svg',
  },
  {
    name: 'Brazil',
    id: 'BR',
    capital: 'Brasília',
    region: 'SA',
    currency: {
      id: 'BRL',
      name: 'Brazilian real',
      symbol: 'R$',
    },
    language: {
      id: 'pt',
      name: 'Portuguese',
    },
    flag: 'https://restcountries.eu/data/bra.svg',
  },
  {
    name: 'British Indian Ocean Territory',
    id: 'IO',
    capital: 'Diego Garcia',
    region: 'AF',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/iot.svg',
  },
  {
    name: 'United States Minor Outlying Islands',
    id: 'UM',
    capital: '',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States Dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/umi.svg',
  },
  {
    name: 'Virgin Islands (British)',
    id: 'VG',
    capital: 'Road Town',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/vgb.svg',
  },
  {
    name: 'Virgin Islands (U.S.)',
    id: 'VI',
    capital: 'Charlotte Amalie',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/vir.svg',
  },
  {
    name: 'Brunei Darussalam',
    id: 'BN',
    capital: 'Bandar Seri Begawan',
    region: 'AS',
    currency: {
      id: 'BND',
      name: 'Brunei dollar',
      symbol: '$',
    },
    language: {
      id: 'ms',
      name: 'Malay',
    },
    flag: 'https://restcountries.eu/data/brn.svg',
  },
  {
    name: 'Bulgaria',
    id: 'BG',
    capital: 'Sofia',
    region: 'EU',
    currency: {
      id: 'BGN',
      name: 'Bulgarian lev',
      symbol: 'лв',
    },
    language: {
      id: 'bg',
      name: 'Bulgarian',
    },
    flag: 'https://restcountries.eu/data/bgr.svg',
  },
  {
    name: 'Burkina Faso',
    id: 'BF',
    capital: 'Ouagadougou',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/bfa.svg',
  },
  {
    name: 'Burundi',
    id: 'BI',
    capital: 'Bujumbura',
    region: 'AF',
    currency: {
      id: 'BIF',
      name: 'Burundian franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/bdi.svg',
  },
  {
    name: 'Cambodia',
    id: 'KH',
    capital: 'Phnom Penh',
    region: 'AS',
    currency: {
      id: 'KHR',
      name: 'Cambodian riel',
      symbol: '៛',
    },
    language: {
      id: 'km',
      name: 'Khmer',
    },
    flag: 'https://restcountries.eu/data/khm.svg',
  },
  {
    name: 'Cameroon',
    id: 'CM',
    capital: 'Yaoundé',
    region: 'AF',
    currency: {
      id: 'XAF',
      name: 'Central African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/cmr.svg',
  },
  {
    name: 'Canada',
    id: 'CA',
    capital: 'Ottawa',
    region: 'NA',
    currency: {
      id: 'CAD',
      name: 'Canadian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/can.svg',
  },
  {
    name: 'Cabo Verde',
    id: 'CV',
    capital: 'Praia',
    region: 'AF',
    currency: {
      id: 'CVE',
      name: 'Cape Verdean escudo',
      symbol: 'Esc',
    },
    language: {
      id: 'pt',
      iso639_2: 'por',
      name: 'Portuguese',
      nativeName: 'Português',
    },
    flag: 'https://restcountries.eu/data/cpv.svg',
  },
  {
    name: 'Cayman Islands',
    id: 'KY',
    capital: 'George Town',
    region: 'NA',
    demonym: 'Caymanian',
    currency: {
      id: 'KYD',
      name: 'Cayman Islands dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/cym.svg',
  },
  {
    name: 'Central African Republic',
    id: 'CF',
    capital: 'Bangui',
    region: 'AF',
    currency: {
      id: 'XAF',
      name: 'Central African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/caf.svg',
  },
  {
    name: 'Chad',
    id: 'TD',
    capital: "N'Djamena",
    region: 'AF',
    currency: {
      id: 'XAF',
      name: 'Central African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/tcd.svg',
  },
  {
    name: 'Chile',
    id: 'CL',
    capital: 'Santiago',
    region: 'SA',
    currency: {
      id: 'CLP',
      name: 'Chilean peso',
      symbol: '$',
    },
    language: {
      id: 'es',
      iso639_2: 'spa',
      name: 'Spanish',
      nativeName: 'Español',
    },
    flag: 'https://restcountries.eu/data/chl.svg',
  },
  {
    name: 'China',
    id: 'CN',
    capital: 'Beijing',
    region: 'AS',
    currency: {
      id: 'CNY',
      name: 'Chinese yuan',
      symbol: '¥',
    },
    language: {
      id: 'zh',
      name: 'Chinese',
    },
    flag: 'https://restcountries.eu/data/chn.svg',
  },
  {
    name: 'Christmas Island',
    id: 'CX',
    capital: 'Flying Fish Cove',
    region: 'OC',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/cxr.svg',
  },
  {
    name: 'Cocos (Keeling) Islands',
    id: 'CC',
    capital: 'West Island',
    region: 'OC',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/cck.svg',
  },
  {
    name: 'Colombia',
    id: 'CO',
    capital: 'Bogotá',
    region: 'SA',
    currency: {
      id: 'COP',
      name: 'Colombian peso',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/col.svg',
  },
  {
    name: 'Comoros',
    id: 'KM',
    capital: 'Moroni',
    region: 'AF',
    currency: {
      id: 'KMF',
      name: 'Comorian franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/com.svg',
  },
  {
    name: 'Congo',
    id: 'CG',
    capital: 'Brazzaville',
    region: 'AF',
    currency: {
      id: 'XAF',
      name: 'Central African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/cog.svg',
  },
  {
    name: 'Congo (Democratic Republic of the)',
    id: 'CD',
    capital: 'Kinshasa',
    region: 'AF',
    currency: {
      id: 'CDF',
      name: 'Congolese franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/cod.svg',
  },
  {
    name: 'Cook Islands',
    id: 'CK',
    capital: 'Avarua',
    region: 'OC',
    currency: {
      id: 'NZD',
      name: 'New Zealand dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/cok.svg',
  },
  {
    name: 'Costa Rica',
    id: 'CR',
    capital: 'San José',
    region: 'NA',
    currency: {
      id: 'CRC',
      name: 'Costa Rican colón',
      symbol: '₡',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/cri.svg',
  },
  {
    name: 'Croatia',
    id: 'HR',
    capital: 'Zagreb',
    region: 'EU',
    currency: {
      id: 'HRK',
      name: 'Croatian kuna',
      symbol: 'kn',
    },
    language: {
      id: 'hr',
      name: 'Croatian',
    },
    flag: 'https://restcountries.eu/data/hrv.svg',
  },
  {
    name: 'Cuba',
    id: 'CU',
    capital: 'Havana',
    region: 'NA',
    currency: {
      id: 'CUC',
      name: 'Cuban convertible peso',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/cub.svg',
  },
  {
    name: 'Curaçao',
    id: 'CW',
    capital: 'Willemstad',
    region: 'SA',
    currency: {
      id: 'ANG',
      name: 'Netherlands Antillean guilder',
      symbol: 'ƒ',
    },
    language: {
      id: 'nl',
      name: 'Dutch',
    },
    flag: 'https://restcountries.eu/data/cuw.svg',
  },
  {
    name: 'Cyprus',
    id: 'CY',
    capital: 'Nicosia',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'tr',
      name: 'Turkish',
    },
    flag: 'https://restcountries.eu/data/cyp.svg',
  },
  {
    name: 'Czech Republic',
    id: 'CZ',
    capital: 'Prague',
    region: 'EU',
    currency: {
      id: 'CZK',
      name: 'Czech koruna',
      symbol: 'Kč',
    },
    language: {
      id: 'cs',
      name: 'Czech',
    },
    flag: 'https://restcountries.eu/data/cze.svg',
  },
  {
    name: 'Denmark',
    id: 'DK',
    capital: 'Copenhagen',
    region: 'EU',
    currency: {
      id: 'DKK',
      name: 'Danish krone',
      symbol: 'kr',
    },
    language: {
      id: 'da',
      name: 'Danish',
    },
    flag: 'https://restcountries.eu/data/dnk.svg',
  },
  {
    name: 'Djibouti',
    id: 'DJ',
    capital: 'Djibouti',
    region: 'AF',
    currency: {
      id: 'DJF',
      name: 'Djiboutian franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/dji.svg',
  },
  {
    name: 'Dominica',
    id: 'DM',
    capital: 'Roseau',
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/dma.svg',
  },
  {
    name: 'Dominican Republic',
    id: 'DO',
    capital: 'Santo Domingo',
    region: 'NA',
    currency: {
      id: 'DOP',
      name: 'Dominican peso',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/dom.svg',
  },
  {
    name: 'Ecuador',
    id: 'EC',
    capital: 'Quito',
    region: 'SA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/ecu.svg',
  },
  {
    name: 'Egypt',
    id: 'EG',
    capital: 'Cairo',
    region: 'AF',
    currency: {
      id: 'EGP',
      name: 'Egyptian pound',
      symbol: '£',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/egy.svg',
  },
  {
    name: 'El Salvador',
    id: 'SV',
    capital: 'San Salvador',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/slv.svg',
  },
  {
    name: 'Equatorial Guinea',
    id: 'GQ',
    capital: 'Malabo',
    region: 'AF',
    currency: {
      id: 'XAF',
      name: 'Central African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'es',
      iso639_2: 'spa',
      name: 'Spanish',
      nativeName: 'Español',
    },
    flag: 'https://restcountries.eu/data/gnq.svg',
  },
  {
    name: 'Eritrea',
    id: 'ER',
    capital: 'Asmara',
    region: 'AF',
    currency: {
      id: 'ERN',
      name: 'Eritrean nakfa',
      symbol: 'Nfk',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/eri.svg',
  },
  {
    name: 'Estonia',
    id: 'EE',
    capital: 'Tallinn',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'et',
      name: 'Estonian',
    },
    flag: 'https://restcountries.eu/data/est.svg',
  },
  {
    name: 'Ethiopia',
    id: 'ET',
    capital: 'Addis Ababa',
    region: 'AF',
    currency: {
      id: 'ETB',
      name: 'Ethiopian birr',
      symbol: 'Br',
    },
    language: {
      id: 'am',
      name: 'Amharic',
    },
    flag: 'https://restcountries.eu/data/eth.svg',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    id: 'FK',
    capital: 'Stanley',
    region: 'SA',
    currency: {
      id: 'FKP',
      name: 'Falkland Islands pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/flk.svg',
  },
  {
    name: 'Faroe Islands',
    id: 'FO',
    capital: 'Tórshavn',
    region: 'EU',
    currency: {
      id: 'DKK',
      name: 'Danish krone',
      symbol: 'kr',
    },
    language: {
      id: 'fo',
      name: 'Faroese',
    },
    flag: 'https://restcountries.eu/data/fro.svg',
  },
  {
    name: 'Fiji',
    id: 'FJ',
    capital: 'Suva',
    region: 'OC',
    currency: {
      id: 'FJD',
      name: 'Fijian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/fji.svg',
  },
  {
    name: 'Finland',
    id: 'FI',
    capital: 'Helsinki',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fi',
      iso639_2: 'fin',
      name: 'Finnish',
      nativeName: 'suomi',
    },
    flag: 'https://restcountries.eu/data/fin.svg',
  },
  {
    name: 'France',
    id: 'FR',
    capital: 'Paris',
    region: 'EU',
    demonym: 'French',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/fra.svg',
  },
  {
    name: 'French Guiana',
    id: 'GF',
    capital: 'Cayenne',
    region: 'SA',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/guf.svg',
  },
  {
    name: 'French Polynesia',
    id: 'PF',
    capital: 'Papeetē',
    region: 'OC',
    currency: {
      id: 'XPF',
      name: 'CFP franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/pyf.svg',
  },
  {
    name: 'French Southern Territories',
    id: 'TF',
    capital: 'Port-aux-Français',
    region: 'AF',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/atf.svg',
  },
  {
    name: 'Gabon',
    id: 'GA',
    capital: 'Libreville',
    region: 'AF',
    currency: {
      id: 'XAF',
      name: 'Central African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/gab.svg',
  },
  {
    name: 'Gambia',
    id: 'GM',
    capital: 'Banjul',
    region: 'AF',
    currency: {
      id: 'GMD',
      name: 'Gambian dalasi',
      symbol: 'D',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/gmb.svg',
  },
  {
    name: 'Georgia',
    id: 'GE',
    capital: 'Tbilisi',
    region: 'AS',
    currency: {
      id: 'GEL',
      name: 'Georgian Lari',
      symbol: 'ლ',
    },
    language: {
      id: 'ka',
      name: 'Georgian',
    },
    flag: 'https://restcountries.eu/data/geo.svg',
  },
  {
    name: 'Germany',
    id: 'DE',
    capital: 'Berlin',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'de',
      name: 'German',
    },
    flag: 'https://restcountries.eu/data/deu.svg',
  },
  {
    name: 'Ghana',
    id: 'GH',
    capital: 'Accra',
    region: 'AF',
    currency: {
      id: 'GHS',
      name: 'Ghanaian cedi',
      symbol: '₵',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/gha.svg',
  },
  {
    name: 'Gibraltar',
    id: 'GI',
    capital: 'Gibraltar',
    region: 'EU',
    currency: {
      id: 'GIP',
      name: 'Gibraltar pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/gib.svg',
  },
  {
    name: 'Greece',
    id: 'GR',
    capital: 'Athens',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'el',
      name: 'Greek (modern)',
    },
    flag: 'https://restcountries.eu/data/grc.svg',
  },
  {
    name: 'Greenland',
    id: 'GL',
    capital: 'Nuuk',
    region: 'NA',
    currency: {
      id: 'DKK',
      name: 'Danish krone',
      symbol: 'kr',
    },
    language: {
      id: 'kl',
      name: 'Kalaallisut',
    },
    flag: 'https://restcountries.eu/data/grl.svg',
  },
  {
    name: 'Grenada',
    id: 'GD',
    capital: "St. George's",
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/grd.svg',
  },
  {
    name: 'Guadeloupe',
    id: 'GP',
    capital: 'Basse-Terre',
    region: 'NA',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/glp.svg',
  },
  {
    name: 'Guam',
    id: 'GU',
    capital: 'Hagåtña',
    region: 'OC',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/gum.svg',
  },
  {
    name: 'Guatemala',
    id: 'GT',
    capital: 'Guatemala City',
    region: 'NA',
    currency: {
      id: 'GTQ',
      name: 'Guatemalan quetzal',
      symbol: 'Q',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/gtm.svg',
  },
  {
    name: 'Guernsey',
    id: 'GG',
    capital: 'St. Peter Port',
    region: 'EU',
    currency: {
      id: 'GBP',
      name: 'British pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/ggy.svg',
  },
  {
    name: 'Guinea',
    id: 'GN',
    capital: 'Conakry',
    region: 'AF',
    currency: {
      id: 'GNF',
      name: 'Guinean franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/gin.svg',
  },
  {
    name: 'Guinea-Bissau',
    id: 'GW',
    capital: 'Bissau',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'pt',
      name: 'Portuguese',
    },
    flag: 'https://restcountries.eu/data/gnb.svg',
  },
  {
    name: 'Guyana',
    id: 'GY',
    capital: 'Georgetown',
    region: 'SA',
    currency: {
      id: 'GYD',
      name: 'Guyanese dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/guy.svg',
  },
  {
    name: 'Haiti',
    id: 'HT',
    capital: 'Port-au-Prince',
    region: 'Americas',
    currency: {
      id: 'HTG',
      name: 'Haitian gourde',
      symbol: 'G',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/hti.svg',
  },
  {
    name: 'Heard Island and McDonald Islands',
    id: 'HM',
    capital: '',
    region: '',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/hmd.svg',
  },
  {
    name: 'Holy See',
    id: 'VA',
    capital: 'Rome',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/vat.svg',
  },
  {
    name: 'Honduras',
    id: 'HN',
    capital: 'Tegucigalpa',
    region: 'NA',
    currency: {
      id: 'HNL',
      name: 'Honduran lempira',
      symbol: 'L',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/hnd.svg',
  },
  {
    name: 'Hong Kong',
    id: 'HK',
    capital: 'City of Victoria',
    region: 'AS',
    currency: {
      id: 'HKD',
      name: 'Hong Kong dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/hkg.svg',
  },
  {
    name: 'Hungary',
    id: 'HU',
    capital: 'Budapest',
    region: 'EU',
    currency: {
      id: 'HUF',
      name: 'Hungarian forint',
      symbol: 'Ft',
    },
    language: {
      id: 'hu',
      name: 'Hungarian',
    },
    flag: 'https://restcountries.eu/data/hun.svg',
  },
  {
    name: 'Iceland',
    id: 'IS',
    capital: 'Reykjavík',
    region: 'EU',
    currency: {
      id: 'ISK',
      name: 'Icelandic króna',
      symbol: 'kr',
    },
    language: {
      id: 'is',
      name: 'Icelandic',
    },
    flag: 'https://restcountries.eu/data/isl.svg',
  },
  {
    name: 'India',
    id: 'IN',
    capital: 'New Delhi',
    region: 'AS',
    currency: {
      id: 'INR',
      name: 'Indian rupee',
      symbol: '₹',
    },
    language: {
      id: 'hi',
      name: 'Hindi',
    },
    flag: 'https://restcountries.eu/data/ind.svg',
  },
  {
    name: 'Indonesia',
    id: 'ID',
    capital: 'Jakarta',
    region: 'AS',
    currency: {
      id: 'IDR',
      name: 'Indonesian rupiah',
      symbol: 'Rp',
    },
    language: {
      id: 'id',
      name: 'Indonesian',
    },
    flag: 'https://restcountries.eu/data/idn.svg',
  },
  {
    name: "Côte d'Ivoire",
    id: 'CI',
    capital: 'Yamoussoukro',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/civ.svg',
  },
  {
    name: 'Iran (Islamic Republic of)',
    id: 'IR',
    capital: 'Tehran',
    region: 'AS',
    currency: {
      id: 'IRR',
      name: 'Iranian rial',
      symbol: '﷼',
    },
    language: {
      id: 'fa',
      name: 'Persian (Farsi)',
    },
    flag: 'https://restcountries.eu/data/irn.svg',
  },
  {
    name: 'Iraq',
    id: 'IQ',
    capital: 'Baghdad',
    region: 'AS',
    currency: {
      id: 'IQD',
      name: 'Iraqi dinar',
      symbol: 'ع.د',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/irq.svg',
  },
  {
    name: 'Ireland',
    id: 'IE',
    capital: 'Dublin',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'ga',
      name: 'Irish',
    },
    flag: 'https://restcountries.eu/data/irl.svg',
  },
  {
    name: 'Isle of Man',
    id: 'IM',
    capital: 'Douglas',
    region: 'EU',
    currency: {
      id: 'GBP',
      name: 'British pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/imn.svg',
  },
  {
    name: 'Israel',
    id: 'IL',
    capital: 'Jerusalem',
    region: 'AS',
    currency: {
      id: 'ILS',
      name: 'Israeli new shekel',
      symbol: '₪',
    },
    language: {
      id: 'he',
      name: 'Hebrew (modern)',
    },
    flag: 'https://restcountries.eu/data/isr.svg',
  },
  {
    name: 'Italy',
    id: 'IT',
    capital: 'Rome',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'it',
      name: 'Italian',
    },
    flag: 'https://restcountries.eu/data/ita.svg',
  },
  {
    name: 'Jamaica',
    id: 'JM',
    capital: 'Kingston',
    region: 'NA',
    currency: {
      id: 'JMD',
      name: 'Jamaican dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/jam.svg',
  },
  {
    name: 'Japan',
    id: 'JP',
    capital: 'Tokyo',
    region: 'AS',
    currency: {
      id: 'JPY',
      name: 'Japanese yen',
      symbol: '¥',
    },
    language: {
      id: 'ja',
      name: 'Japanese',
    },
    flag: 'https://restcountries.eu/data/jpn.svg',
  },
  {
    name: 'Jersey',
    id: 'JE',
    capital: 'Saint Helier',
    region: 'EU',
    currency: {
      id: 'GBP',
      name: 'British pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      iso639_2: 'eng',
      name: 'English',
      nativeName: 'English',
    },
    flag: 'https://restcountries.eu/data/jey.svg',
  },
  {
    name: 'Jordan',
    id: 'JO',
    capital: 'Amman',
    region: 'AS',
    currency: {
      id: 'JOD',
      name: 'Jordanian dinar',
      symbol: 'د.ا',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/jor.svg',
  },
  {
    name: 'Kazakhstan',
    id: 'KZ',
    capital: 'Astana',
    region: 'AS',
    currency: {
      id: 'KZT',
      name: 'Kazakhstani tenge',
      symbol: null,
    },
    language: {
      id: 'kk',
      name: 'Kazakh',
    },
    flag: 'https://restcountries.eu/data/kaz.svg',
  },
  {
    name: 'Kenya',
    id: 'KE',
    capital: 'Nairobi',
    region: 'AF',
    currency: {
      id: 'KES',
      name: 'Kenyan shilling',
      symbol: 'Sh',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/ken.svg',
  },
  {
    name: 'Kiribati',
    id: 'KI',
    capital: 'South Tarawa',
    region: 'OC',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/kir.svg',
  },
  {
    name: 'Kuwait',
    id: 'KW',
    capital: 'Kuwait City',
    region: 'AS',
    currency: {
      id: 'KWD',
      name: 'Kuwaiti dinar',
      symbol: 'د.ك',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/kwt.svg',
  },
  {
    name: 'Kyrgyzstan',
    id: 'KG',
    capital: 'Bishkek',
    region: 'AS',
    currency: {
      id: 'KGS',
      name: 'Kyrgyzstani som',
      symbol: 'с',
    },
    language: {
      id: 'ky',
      name: 'Kyrgyz',
    },
    flag: 'https://restcountries.eu/data/kgz.svg',
  },
  {
    name: "Lao People's Democratic Republic",
    id: 'LA',
    capital: 'Vientiane',
    region: 'AS',
    currency: {
      id: 'LAK',
      name: 'Lao kip',
      symbol: '₭',
    },
    language: {
      id: 'lo',
      name: 'Lao',
    },
    flag: 'https://restcountries.eu/data/lao.svg',
  },
  {
    name: 'Latvia',
    id: 'LV',
    capital: 'Riga',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'lv',
      name: 'Latvian',
    },
    flag: 'https://restcountries.eu/data/lva.svg',
  },
  {
    name: 'Lebanon',
    id: 'LB',
    capital: 'Beirut',
    region: 'AS',
    currency: {
      id: 'LBP',
      name: 'Lebanese pound',
      symbol: 'ل.ل',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/lbn.svg',
  },
  {
    name: 'Lesotho',
    id: 'LS',
    capital: 'Maseru',
    region: 'AF',
    currency: {
      id: 'LSL',
      name: 'Lesotho loti',
      symbol: 'L',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/lso.svg',
  },
  {
    name: 'Liberia',
    id: 'LR',
    capital: 'Monrovia',
    region: 'AF',
    currency: {
      id: 'LRD',
      name: 'Liberian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/lbr.svg',
  },
  {
    name: 'Libya',
    id: 'LY',
    capital: 'Tripoli',
    region: 'AF',
    currency: {
      id: 'LYD',
      name: 'Libyan dinar',
      symbol: 'ل.د',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/lby.svg',
  },
  {
    name: 'Liechtenstein',
    id: 'LI',
    capital: 'Vaduz',
    region: 'EU',
    currency: {
      id: 'CHF',
      name: 'Swiss franc',
      symbol: 'Fr',
    },
    language: {
      id: 'de',
      name: 'German',
    },
    flag: 'https://restcountries.eu/data/lie.svg',
  },
  {
    name: 'Lithuania',
    id: 'LT',
    capital: 'Vilnius',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'lt',
      name: 'Lithuanian',
    },
    flag: 'https://restcountries.eu/data/ltu.svg',
  },
  {
    name: 'Luxembourg',
    id: 'LU',
    capital: 'Luxembourg',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/lux.svg',
  },
  {
    name: 'Macao',
    id: 'MO',
    capital: '',
    region: 'AS',
    currency: {
      id: 'MOP',
      name: 'Macanese pataca',
      symbol: 'P',
    },
    language: {
      id: 'zh',
      name: 'Chinese',
    },
    flag: 'https://restcountries.eu/data/mac.svg',
  },
  {
    name: 'Macedonia (the former Yugoslav Republic of)',
    id: 'MK',
    capital: 'Skopje',
    region: 'EU',
    currency: {
      id: 'MKD',
      name: 'Macedonian denar',
      symbol: 'ден',
    },
    language: {
      id: 'mk',
      name: 'Macedonian',
    },
    flag: 'https://restcountries.eu/data/mkd.svg',
  },
  {
    name: 'Madagascar',
    id: 'MG',
    capital: 'Antananarivo',
    region: 'AF',
    currency: {
      id: 'MGA',
      name: 'Malagasy ariary',
      symbol: 'Ar',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/mdg.svg',
  },
  {
    name: 'Malawi',
    id: 'MW',
    capital: 'Lilongwe',
    region: 'AF',
    currency: {
      id: 'MWK',
      name: 'Malawian kwacha',
      symbol: 'MK',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/mwi.svg',
  },
  {
    name: 'Malaysia',
    id: 'MY',
    capital: 'Kuala Lumpur',
    region: 'AS',
    currency: {
      id: 'MYR',
      name: 'Malaysian ringgit',
      symbol: 'RM',
    },
    language: {
      id: null,
      name: 'Malaysian',
    },
    flag: 'https://restcountries.eu/data/mys.svg',
  },
  {
    name: 'Maldives',
    id: 'MV',
    capital: 'Malé',
    region: 'AS',
    currency: {
      id: 'MVR',
      name: 'Maldivian rufiyaa',
      symbol: '.ރ',
    },
    language: {
      id: 'dv',
      name: 'Divehi',
    },
    flag: 'https://restcountries.eu/data/mdv.svg',
  },
  {
    name: 'Mali',
    id: 'ML',
    capital: 'Bamako',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/mli.svg',
  },
  {
    name: 'Malta',
    id: 'MT',
    capital: 'Valletta',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'mt',
      name: 'Maltese',
    },
    flag: 'https://restcountries.eu/data/mlt.svg',
  },
  {
    name: 'Marshall Islands',
    id: 'MH',
    capital: 'Majuro',
    region: 'OC',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/mhl.svg',
  },
  {
    name: 'Martinique',
    id: 'MQ',
    capital: 'Fort-de-France',
    region: 'Americas',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/mtq.svg',
  },
  {
    name: 'Mauritania',
    id: 'MR',
    capital: 'Nouakchott',
    region: 'AF',
    currency: {
      id: 'MRO',
      name: 'Mauritanian ouguiya',
      symbol: 'UM',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/mrt.svg',
  },
  {
    name: 'Mauritius',
    id: 'MU',
    capital: 'Port Louis',
    region: 'AF',
    currency: {
      id: 'MUR',
      name: 'Mauritian rupee',
      symbol: '₨',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/mus.svg',
  },
  {
    name: 'Mayotte',
    id: 'YT',
    capital: 'Mamoudzou',
    region: 'AF',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/myt.svg',
  },
  {
    name: 'Mexico',
    id: 'MX',
    capital: 'Mexico City',
    region: 'NA',
    currency: {
      id: 'MXN',
      name: 'Mexican peso',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/mex.svg',
  },
  {
    name: 'Micronesia (Federated States of)',
    id: 'FM',
    capital: 'Palikir',
    region: 'OC',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/fsm.svg',
  },
  {
    name: 'Moldova (Republic of)',
    id: 'MD',
    capital: 'Chișinău',
    region: 'EU',
    currency: {
      id: 'MDL',
      name: 'Moldovan leu',
      symbol: 'L',
    },
    language: {
      id: 'ro',
      name: 'Romanian',
    },
    flag: 'https://restcountries.eu/data/mda.svg',
  },
  {
    name: 'Monaco',
    id: 'MC',
    capital: 'Monaco',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/mco.svg',
  },
  {
    name: 'Mongolia',
    id: 'MN',
    capital: 'Ulan Bator',
    region: 'AS',
    currency: {
      id: 'MNT',
      name: 'Mongolian tögrög',
      symbol: '₮',
    },
    language: {
      id: 'mn',
      name: 'Mongolian',
    },
    flag: 'https://restcountries.eu/data/mng.svg',
  },
  {
    name: 'Montenegro',
    id: 'ME',
    capital: 'Podgorica',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'sr',
      name: 'Serbian',
    },
    flag: 'https://restcountries.eu/data/mne.svg',
  },
  {
    name: 'Montserrat',
    id: 'MS',
    capital: 'Plymouth',
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/msr.svg',
  },
  {
    name: 'Morocco',
    id: 'MA',
    capital: 'Rabat',
    region: 'AF',
    currency: {
      id: 'MAD',
      name: 'Moroccan dirham',
      symbol: 'د.م.',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/mar.svg',
  },
  {
    name: 'Mozambique',
    id: 'MZ',
    capital: 'Maputo',
    region: 'AF',
    currency: {
      id: 'MZN',
      name: 'Mozambican metical',
      symbol: 'MT',
    },
    language: {
      id: 'pt',
      name: 'Portuguese',
    },
    flag: 'https://restcountries.eu/data/moz.svg',
  },
  {
    name: 'Myanmar',
    id: 'MM',
    capital: 'Naypyidaw',
    region: 'AS',
    currency: {
      id: 'MMK',
      name: 'Burmese kyat',
      symbol: 'Ks',
    },
    language: {
      id: 'my',
      name: 'Burmese',
    },
    flag: 'https://restcountries.eu/data/mmr.svg',
  },
  {
    name: 'Namibia',
    id: 'NA',
    capital: 'Windhoek',
    region: 'AF',
    currency: {
      id: 'NAD',
      name: 'Namibian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/nam.svg',
  },
  {
    name: 'Nauru',
    id: 'NR',
    capital: 'Yaren',
    region: 'OC',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/nru.svg',
  },
  {
    name: 'Nepal',
    id: 'NP',
    capital: 'Kathmandu',
    region: 'AS',
    currency: {
      id: 'NPR',
      name: 'Nepalese rupee',
      symbol: '₨',
    },
    language: {
      id: 'ne',
      name: 'Nepali',
    },
    flag: 'https://restcountries.eu/data/npl.svg',
  },
  {
    name: 'Netherlands',
    id: 'NL',
    capital: 'Amsterdam',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'nl',
      name: 'Dutch',
    },
    flag: 'https://restcountries.eu/data/nld.svg',
  },
  {
    name: 'New Caledonia',
    id: 'NC',
    capital: 'Nouméa',
    region: 'OC',
    currency: {
      id: 'XPF',
      name: 'CFP franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/ncl.svg',
  },
  {
    name: 'New Zealand',
    id: 'NZ',
    capital: 'Wellington',
    region: 'OC',
    currency: {
      id: 'NZD',
      name: 'New Zealand dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/nzl.svg',
  },
  {
    name: 'Nicaragua',
    id: 'NI',
    capital: 'Managua',
    region: 'NA',
    currency: {
      id: 'NIO',
      name: 'Nicaraguan córdoba',
      symbol: 'C$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/nic.svg',
  },
  {
    name: 'Niger',
    id: 'NE',
    capital: 'Niamey',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/ner.svg',
  },
  {
    name: 'Nigeria',
    id: 'NG',
    capital: 'Abuja',
    region: 'AF',
    currency: {
      id: 'NGN',
      name: 'Nigerian naira',
      symbol: '₦',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/nga.svg',
  },
  {
    name: 'Niue',
    id: 'NU',
    capital: 'Alofi',
    region: 'OC',
    currency: {
      id: 'NZD',
      name: 'New Zealand dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/niu.svg',
  },
  {
    name: 'Norfolk Island',
    id: 'NF',
    capital: 'Kingston',
    region: 'OC',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/nfk.svg',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    id: 'KP',
    capital: 'Pyongyang',
    region: 'AS',
    currency: {
      id: 'KPW',
      name: 'North Korean won',
      symbol: '₩',
    },
    language: {
      id: 'ko',
      name: 'Korean',
    },
    flag: 'https://restcountries.eu/data/prk.svg',
  },
  {
    name: 'Northern Mariana Islands',
    id: 'MP',
    capital: 'Saipan',
    region: 'OC',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/mnp.svg',
  },
  {
    name: 'Norway',
    id: 'NO',
    capital: 'Oslo',
    region: 'EU',
    currency: {
      id: 'NOK',
      name: 'Norwegian krone',
      symbol: 'kr',
    },
    language: {
      id: 'no',
      name: 'Norwegian',
    },
    flag: 'https://restcountries.eu/data/nor.svg',
  },
  {
    name: 'Oman',
    id: 'OM',
    capital: 'Muscat',
    region: 'AS',
    currency: {
      id: 'OMR',
      name: 'Omani rial',
      symbol: 'ر.ع.',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/omn.svg',
  },
  {
    name: 'Pakistan',
    id: 'PK',
    capital: 'Islamabad',
    region: 'AS',
    currency: {
      id: 'PKR',
      name: 'Pakistani rupee',
      symbol: '₨',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/pak.svg',
  },
  {
    name: 'Palau',
    id: 'PW',
    capital: 'Ngerulmud',
    region: 'OC',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/plw.svg',
  },
  {
    name: 'Palestine, State of',
    id: 'PS',
    capital: 'Ramallah',
    region: 'AS',
    currency: {
      id: 'ILS',
      name: 'Israeli new sheqel',
      symbol: '₪',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/pse.svg',
  },
  {
    name: 'Panama',
    id: 'PA',
    capital: 'Panama City',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/pan.svg',
  },
  {
    name: 'Papua New Guinea',
    id: 'PG',
    capital: 'Port Moresby',
    region: 'OC',
    currency: {
      id: 'PGK',
      name: 'Papua New Guinean kina',
      symbol: 'K',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/png.svg',
  },
  {
    name: 'Paraguay',
    id: 'PY',
    capital: 'Asunción',
    region: 'SA',
    currency: {
      id: 'PYG',
      name: 'Paraguayan guaraní',
      symbol: '₲',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/pry.svg',
  },
  {
    name: 'Peru',
    id: 'PE',
    capital: 'Lima',
    region: 'SA',
    currency: {
      id: 'PEN',
      name: 'Peruvian sol',
      symbol: 'S/.',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/per.svg',
  },
  {
    name: 'Philippines',
    id: 'PH',
    capital: 'Manila',
    region: 'AS',
    currency: {
      id: 'PHP',
      name: 'Philippine peso',
      symbol: '₱',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/phl.svg',
  },
  {
    name: 'Pitcairn',
    id: 'PN',
    capital: 'Adamstown',
    region: 'OC',
    currency: {
      id: 'NZD',
      name: 'New Zealand dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/pcn.svg',
  },
  {
    name: 'Poland',
    id: 'PL',
    capital: 'Warsaw',
    region: 'EU',
    currency: {
      id: 'PLN',
      name: 'Polish złoty',
      symbol: 'zł',
    },
    language: {
      id: 'pl',
      name: 'Polish',
    },
    flag: 'https://restcountries.eu/data/pol.svg',
  },
  {
    name: 'Portugal',
    id: 'PT',
    capital: 'Lisbon',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'pt',
      name: 'Portuguese',
    },
    flag: 'https://restcountries.eu/data/prt.svg',
  },
  {
    name: 'Puerto Rico',
    id: 'PR',
    capital: 'San Juan',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/pri.svg',
  },
  {
    name: 'Qatar',
    id: 'QA',
    capital: 'Doha',
    region: 'AS',
    currency: {
      id: 'QAR',
      name: 'Qatari riyal',
      symbol: 'ر.ق',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/qat.svg',
  },
  {
    name: 'Republic of Kosovo',
    id: 'XK',
    capital: 'Pristina',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'sq',
      name: 'Albanian',
    },
    flag: 'https://restcountries.eu/data/kos.svg',
  },
  {
    name: 'Réunion',
    id: 'RE',
    capital: 'Saint-Denis',
    region: 'AF',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/reu.svg',
  },
  {
    name: 'Romania',
    id: 'RO',
    capital: 'Bucharest',
    region: 'EU',
    currency: {
      id: 'RON',
      name: 'Romanian leu',
      symbol: 'lei',
    },
    language: {
      id: 'ro',
      name: 'Romanian',
    },
    flag: 'https://restcountries.eu/data/rou.svg',
  },
  {
    name: 'Russian Federation',
    id: 'RU',
    capital: 'Moscow',
    region: 'EU',
    currency: {
      id: 'RUB',
      name: 'Russian ruble',
      symbol: '₽',
    },
    language: {
      id: 'ru',
      name: 'Russian',
    },
    flag: 'https://restcountries.eu/data/rus.svg',
  },
  {
    name: 'Rwanda',
    id: 'RW',
    capital: 'Kigali',
    region: 'AF',
    currency: {
      id: 'RWF',
      name: 'Rwandan franc',
      symbol: 'Fr',
    },
    language: {
      id: 'rw',
      name: 'Kinyarwanda',
    },
    flag: 'https://restcountries.eu/data/rwa.svg',
  },
  {
    name: 'Saint Barthélemy',
    id: 'BL',
    capital: 'Gustavia',
    region: 'NA',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/blm.svg',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    id: 'SH',
    capital: 'Jamestown',
    region: 'AF',
    currency: {
      id: 'SHP',
      name: 'Saint Helena pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/shn.svg',
  },
  {
    name: 'Saint Kitts and Nevis',
    id: 'KN',
    capital: 'Basseterre',
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/kna.svg',
  },
  {
    name: 'Saint Lucia',
    id: 'LC',
    capital: 'Castries',
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/lca.svg',
  },
  {
    name: 'Saint Martin (French part)',
    id: 'MF',
    capital: 'Marigot',
    region: 'NA',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/maf.svg',
  },
  {
    name: 'Saint Pierre and Miquelon',
    id: 'PM',
    capital: 'Saint-Pierre',
    region: 'NA',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/spm.svg',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    id: 'VC',
    capital: 'Kingstown',
    region: 'NA',
    currency: {
      id: 'XCD',
      name: 'East Caribbean dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/vct.svg',
  },
  {
    name: 'Samoa',
    id: 'WS',
    capital: 'Apia',
    region: 'OC',
    currency: {
      id: 'WST',
      name: 'Samoan tālā',
      symbol: 'T',
    },
    language: {
      id: 'sm',
      name: 'Samoan',
    },
    flag: 'https://restcountries.eu/data/wsm.svg',
  },
  {
    name: 'San Marino',
    id: 'SM',
    capital: 'City of San Marino',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'it',
      name: 'Italian',
    },
    flag: 'https://restcountries.eu/data/smr.svg',
  },
  {
    name: 'Sao Tome and Principe',
    id: 'ST',
    capital: 'São Tomé',
    region: 'AF',
    currency: {
      id: 'STD',
      name: 'São Tomé and Príncipe dobra',
      symbol: 'Db',
    },
    language: {
      id: 'pt',
      name: 'Portuguese',
    },
    flag: 'https://restcountries.eu/data/stp.svg',
  },
  {
    name: 'Saudi Arabia',
    id: 'SA',
    capital: 'Riyadh',
    region: 'AS',
    currency: {
      id: 'SAR',
      name: 'Saudi riyal',
      symbol: 'ر.س',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/sau.svg',
  },
  {
    name: 'Senegal',
    id: 'SN',
    capital: 'Dakar',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/sen.svg',
  },
  {
    name: 'Serbia',
    id: 'RS',
    capital: 'Belgrade',
    region: 'EU',
    currency: {
      id: 'RSD',
      name: 'Serbian dinar',
      symbol: 'дин.',
    },
    language: {
      id: 'sr',
      name: 'Serbian',
    },
    flag: 'https://restcountries.eu/data/srb.svg',
  },
  {
    name: 'Seychelles',
    id: 'SC',
    capital: 'Victoria',
    region: 'AF',
    currency: {
      id: 'SCR',
      name: 'Seychellois rupee',
      symbol: '₨',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/syc.svg',
  },
  {
    name: 'Sierra Leone',
    id: 'SL',
    capital: 'Freetown',
    region: 'AF',
    currency: {
      id: 'SLL',
      name: 'Sierra Leonean leone',
      symbol: 'Le',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/sle.svg',
  },
  {
    name: 'Singapore',
    id: 'SG',
    capital: 'Singapore',
    region: 'AS',
    currency: {
      id: 'SGD',
      name: 'Singapore dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/sgp.svg',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    id: 'SX',
    capital: 'Philipsburg',
    region: 'Americas',
    currency: {
      id: 'ANG',
      name: 'Netherlands Antillean guilder',
      symbol: 'ƒ',
    },
    language: {
      id: 'nl',
      name: 'Dutch',
    },
    flag: 'https://restcountries.eu/data/sxm.svg',
  },
  {
    name: 'Slovakia',
    id: 'SK',
    capital: 'Bratislava',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'sk',
      name: 'Slovak',
    },
    flag: 'https://restcountries.eu/data/svk.svg',
  },
  {
    name: 'Slovenia',
    id: 'SI',
    capital: 'Ljubljana',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'sl',
      name: 'Slovene',
    },
    flag: 'https://restcountries.eu/data/svn.svg',
  },
  {
    name: 'Solomon Islands',
    id: 'SB',
    capital: 'Honiara',
    region: 'OC',
    currency: {
      id: 'SBD',
      name: 'Solomon Islands dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/slb.svg',
  },
  {
    name: 'Somalia',
    id: 'SO',
    capital: 'Mogadishu',
    region: 'AF',
    currency: {
      id: 'SOS',
      name: 'Somali shilling',
      symbol: 'Sh',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/som.svg',
  },
  {
    name: 'South Africa',
    id: 'ZA',
    capital: 'Pretoria',
    region: 'AF',
    currency: {
      id: 'ZAR',
      name: 'South African rand',
      symbol: 'R',
    },
    language: {
      id: 'en',
      iso639_2: 'eng',
      name: 'English',
      nativeName: 'English',
    },
    flag: 'https://restcountries.eu/data/zaf.svg',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    id: 'GS',
    capital: 'King Edward Point',
    region: 'NA',
    currency: {
      id: 'GBP',
      name: 'British pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/sgs.svg',
  },
  {
    name: 'Korea (Republic of)',
    id: 'KR',
    capital: 'Seoul',
    region: 'AS',
    currency: {
      id: 'KRW',
      name: 'South Korean won',
      symbol: '₩',
    },
    language: {
      id: 'ko',
      name: 'Korean',
    },
    flag: 'https://restcountries.eu/data/kor.svg',
  },
  {
    name: 'South Sudan',
    id: 'SS',
    capital: 'Juba',
    region: 'AF',
    currency: {
      id: 'SSP',
      name: 'South Sudanese pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/ssd.svg',
  },
  {
    name: 'Spain',
    id: 'ES',
    capital: 'Madrid',
    region: 'EU',
    currency: {
      id: 'EUR',
      name: 'Euro',
      symbol: '€',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/esp.svg',
  },
  {
    name: 'Sri Lanka',
    id: 'LK',
    capital: 'Colombo',
    region: 'AS',
    currency: {
      id: 'LKR',
      name: 'Sri Lankan rupee',
      symbol: 'Rs',
    },
    language: {
      id: 'si',
      iso639_2: 'sin',
      name: 'Sinhalese',
      nativeName: 'සිංහල',
    },
    flag: 'https://restcountries.eu/data/lka.svg',
  },
  {
    name: 'Sudan',
    id: 'SD',
    capital: 'Khartoum',
    region: 'AF',
    currency: {
      id: 'SDG',
      name: 'Sudanese pound',
      symbol: 'ج.س.',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/sdn.svg',
  },
  {
    name: 'Suriname',
    id: 'SR',
    capital: 'Paramaribo',
    region: 'SA',
    currency: {
      id: 'SRD',
      name: 'Surinamese dollar',
      symbol: '$',
    },
    language: {
      id: 'nl',
      name: 'Dutch',
    },
    flag: 'https://restcountries.eu/data/sur.svg',
  },
  {
    name: 'Svalbard and Jan Mayen',
    id: 'SJ',
    capital: 'Longyearbyen',
    region: 'EU',
    currency: {
      id: 'NOK',
      name: 'Norwegian krone',
      symbol: 'kr',
    },
    language: {
      id: 'no',
      name: 'Norwegian',
    },
    flag: 'https://restcountries.eu/data/sjm.svg',
  },
  {
    name: 'Swaziland',
    id: 'SZ',
    capital: 'Lobamba',
    region: 'AF',
    currency: {
      id: 'SZL',
      name: 'Swazi lilangeni',
      symbol: 'L',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/swz.svg',
  },
  {
    name: 'Sweden',
    id: 'SE',
    capital: 'Stockholm',
    region: 'EU',
    currency: {
      id: 'SEK',
      name: 'Swedish krona',
      symbol: 'kr',
    },
    language: {
      id: 'sv',
      name: 'Swedish',
    },
    flag: 'https://restcountries.eu/data/swe.svg',
  },
  {
    name: 'Switzerland',
    id: 'CH',
    capital: 'Bern',
    region: 'EU',
    currency: {
      id: 'CHF',
      name: 'Swiss franc',
      symbol: 'Fr',
    },
    language: {
      id: 'de',
      name: 'German',
    },
    flag: 'https://restcountries.eu/data/che.svg',
  },
  {
    name: 'Syrian Arab Republic',
    id: 'SY',
    capital: 'Damascus',
    region: 'AS',
    currency: {
      id: 'SYP',
      name: 'Syrian pound',
      symbol: '£',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/syr.svg',
  },
  {
    name: 'Taiwan',
    id: 'TW',
    capital: 'Taipei',
    region: 'AS',
    currency: {
      id: 'TWD',
      name: 'New Taiwan dollar',
      symbol: '$',
    },
    language: {
      id: 'zh',
      name: 'Chinese',
    },
    flag: 'https://restcountries.eu/data/twn.svg',
  },
  {
    name: 'Tajikistan',
    id: 'TJ',
    capital: 'Dushanbe',
    region: 'AS',
    currency: {
      id: 'TJS',
      name: 'Tajikistani somoni',
      symbol: 'ЅМ',
    },
    language: {
      id: 'tg',
      name: 'Tajik',
    },
    flag: 'https://restcountries.eu/data/tjk.svg',
  },
  {
    name: 'Tanzania, United Republic of',
    id: 'TZ',
    capital: 'Dodoma',
    region: 'AF',
    currency: {
      id: 'TZS',
      name: 'Tanzanian shilling',
      symbol: 'Sh',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/tza.svg',
  },
  {
    name: 'Thailand',
    id: 'TH',
    capital: 'Bangkok',
    region: 'AS',
    currency: {
      id: 'THB',
      name: 'Thai baht',
      symbol: '฿',
    },
    language: {
      id: 'th',
      name: 'Thai',
    },
    flag: 'https://restcountries.eu/data/tha.svg',
  },
  {
    name: 'Timor-Leste',
    id: 'TL',
    capital: 'Dili',
    region: 'AS',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'pt',
      name: 'Portuguese',
    },
    flag: 'https://restcountries.eu/data/tls.svg',
  },
  {
    name: 'Togo',
    id: 'TG',
    capital: 'Lomé',
    region: 'AF',
    currency: {
      id: 'XOF',
      name: 'West African CFA franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/tgo.svg',
  },
  {
    name: 'Tokelau',
    id: 'TK',
    capital: 'Fakaofo',
    region: 'OC',
    currency: {
      id: 'NZD',
      name: 'New Zealand dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/tkl.svg',
  },
  {
    name: 'Tonga',
    id: 'TO',
    capital: "Nuku'alofa",
    region: 'OC',
    currency: {
      id: 'TOP',
      name: 'Tongan paʻanga',
      symbol: 'T$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/ton.svg',
  },
  {
    name: 'Trinidad and Tobago',
    id: 'TT',
    capital: 'Port of Spain',
    region: 'SA',
    currency: {
      id: 'TTD',
      name: 'Trinidad and Tobago dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/tto.svg',
  },
  {
    name: 'Tunisia',
    id: 'TN',
    capital: 'Tunis',
    region: 'AF',
    currency: {
      id: 'TND',
      name: 'Tunisian dinar',
      symbol: 'د.ت',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/tun.svg',
  },
  {
    name: 'Turkey',
    id: 'TR',
    capital: 'Ankara',
    region: 'AS',
    currency: {
      id: 'TRY',
      name: 'Turkish lira',
      symbol: null,
    },
    language: {
      id: 'tr',
      name: 'Turkish',
    },
    flag: 'https://restcountries.eu/data/tur.svg',
  },
  {
    name: 'Turkmenistan',
    id: 'TM',
    capital: 'Ashgabat',
    region: 'AS',
    currency: {
      id: 'TMT',
      name: 'Turkmenistan manat',
      symbol: 'm',
    },
    language: {
      id: 'tk',
      name: 'Turkmen',
    },
    flag: 'https://restcountries.eu/data/tkm.svg',
  },
  {
    name: 'Turks and Caicos Islands',
    id: 'TC',
    capital: 'Cockburn Town',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/tca.svg',
  },
  {
    name: 'Tuvalu',
    id: 'TV',
    capital: 'Funafuti',
    region: 'OC',
    currency: {
      id: 'AUD',
      name: 'Australian dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/tuv.svg',
  },
  {
    name: 'Uganda',
    id: 'UG',
    capital: 'Kampala',
    region: 'AF',
    currency: {
      id: 'UGX',
      name: 'Ugandan shilling',
      symbol: 'Sh',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/uga.svg',
  },
  {
    name: 'Ukraine',
    id: 'UA',
    capital: 'Kiev',
    region: 'EU',
    currency: {
      id: 'UAH',
      name: 'Ukrainian hryvnia',
      symbol: '₴',
    },
    language: {
      id: 'uk',
      name: 'Ukrainian',
    },
    flag: 'https://restcountries.eu/data/ukr.svg',
  },
  {
    name: 'United Arab Emirates',
    id: 'AE',
    capital: 'Abu Dhabi',
    region: 'AS',
    currency: {
      id: 'AED',
      name: 'United Arab Emirates dirham',
      symbol: 'د.إ',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/are.svg',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    id: 'GB',
    capital: 'London',
    region: 'EU',
    currency: {
      id: 'GBP',
      name: 'British pound',
      symbol: '£',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/gbr.svg',
  },
  {
    name: 'United States of America',
    id: 'US',
    capital: 'Washington, D.C.',
    region: 'NA',
    currency: {
      id: 'USD',
      name: 'United States dollar',
      symbol: '$',
    },
    language: {
      id: 'en',
      iso639_2: 'eng',
      name: 'English',
      nativeName: 'English',
    },
    flag: 'https://restcountries.eu/data/usa.svg',
  },
  {
    name: 'Uruguay',
    id: 'UY',
    capital: 'Montevideo',
    region: 'SA',
    currency: {
      id: 'UYU',
      name: 'Uruguayan peso',
      symbol: '$',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/ury.svg',
  },
  {
    name: 'Uzbekistan',
    id: 'UZ',
    capital: 'Tashkent',
    region: 'AS',
    currency: {
      id: 'UZS',
      name: "Uzbekistani so'm",
      symbol: null,
    },
    language: {
      id: 'uz',
      name: 'Uzbek',
    },
    flag: 'https://restcountries.eu/data/uzb.svg',
  },
  {
    name: 'Vanuatu',
    id: 'VU',
    capital: 'Port Vila',
    region: 'OC',
    currency: {
      id: 'VUV',
      name: 'Vanuatu vatu',
      symbol: 'Vt',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/vut.svg',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    id: 'VE',
    capital: 'Caracas',
    region: 'SA',
    currency: {
      id: 'VEF',
      name: 'Venezuelan bolívar',
      symbol: 'Bs F',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/ven.svg',
  },
  {
    name: 'Viet Nam',
    id: 'VN',
    capital: 'Hanoi',
    region: 'AS',
    currency: {
      id: 'VND',
      name: 'Vietnamese đồng',
      symbol: '₫',
    },
    language: {
      id: 'vi',
      name: 'Vietnamese',
    },
    flag: 'https://restcountries.eu/data/vnm.svg',
  },
  {
    name: 'Wallis and Futuna',
    id: 'WF',
    capital: 'Mata-Utu',
    region: 'OC',
    currency: {
      id: 'XPF',
      name: 'CFP franc',
      symbol: 'Fr',
    },
    language: {
      id: 'fr',
      name: 'French',
    },
    flag: 'https://restcountries.eu/data/wlf.svg',
  },
  {
    name: 'Western Sahara',
    id: 'EH',
    capital: 'El Aaiún',
    region: 'AF',
    currency: {
      id: 'MAD',
      name: 'Moroccan dirham',
      symbol: 'د.م.',
    },
    language: {
      id: 'es',
      name: 'Spanish',
    },
    flag: 'https://restcountries.eu/data/esh.svg',
  },
  {
    name: 'Yemen',
    id: 'YE',
    capital: "Sana'a",
    region: 'AS',
    currency: {
      id: 'YER',
      name: 'Yemeni rial',
      symbol: '﷼',
    },
    language: {
      id: 'ar',
      name: 'Arabic',
    },
    flag: 'https://restcountries.eu/data/yem.svg',
  },
  {
    name: 'Zambia',
    id: 'ZM',
    capital: 'Lusaka',
    region: 'AF',
    currency: {
      id: 'ZMW',
      name: 'Zambian kwacha',
      symbol: 'ZK',
    },
    language: {
      id: 'en',
      name: 'English',
    },
    flag: 'https://restcountries.eu/data/zmb.svg',
  },
  {
    name: 'Zimbabwe',
    id: 'ZW',
    capital: 'Harare',
    region: 'AF',
    currency: {
      id: 'BWP',
      name: 'Botswana pula',
      symbol: 'P',
    },
    language: {
      id: 'en',
      iso639_2: 'eng',
      name: 'English',
      nativeName: 'English',
    },
    flag: 'https://restcountries.eu/data/zwe.svg',
  },
];

export default countries;
